### ISSUE TITLE
Elemental-cli to unify UX

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-toolkit#108]
Given the several components involved (and those that will come in the future), it is straightforward to create a single cli that embeds the needed parts from all the involved pieces:

- `luet build` could be easily imported as standalone module and created a separate cli command with the specific defaults set for our use-cases. E.g. `elemental build`
- `luet utils unpack` can be imported / replaced by `elemental pull`. Given that derivatives will have to push their final image to a `:latest` tag for rolling updates, loosing the upgrade channels capabilities. ( see https://github.com/rancher/wharfie for a possible replacement )
- `yip` can be used already as a standalone module and replaced by a `elemental cloudinit`
- Image verification (#107 outcome) by a `elemental verify`
- #56  can become directly `elemental build-iso` and replace the current luet extension, which is just a bash script. This means we could also drop yq and jq from the dependencies
- [cos-setup](https://github.com/rancher-sandbox/cOS-toolkit/blob/master/packages/cos-setup/cos-setup) can be an hypotetical  `elemental run-stage`
- [cos-features](https://github.com/rancher-sandbox/cOS-toolkit/blob/master/packages/cos-features/cos-feature.sh) can become `elemental features enable/disable/list`
- Image builder scripts (arm, raw images, etc) should be part of the CLI. E.g. `elemental build-raw ...`

This have the advantage that we can then tag in a unique piece the moving pieces and decide when to pick new versions of our internal dependencies. 

Besides, we can have one repository containing the CLI and package specs. The package specs can be embedded assets into the binary so they are carried over as part of the binary release. Along with the binaries required by derivatives developers when building a Dockerfile. In this way we have one portable binary which can be both used to rebuild the assets, but also to place them during build in an immutable (and reproducible) way.

## Action Items

To have a replacement for the current feature set, we need:
- [x] #881

Building Images, Packages, Derivatives:

The build part of elemental, should allow us to get rid of the makefiles target, CI specific code to build packages, image building scripts, and luet as a binary dependency.

- [x] #1217
- [x] #1227
- [ ] `elemental build --packages`:  re-use `luet build` code as library to build packages, possibly embedding https://github.com/rancher-sandbox/cOS-toolkit/blob/master/.github/build.go to build package definition from embedded or remote assets
- [ ] `elemental install-packages`: A command that embeds or replaces `luet install` so that can be used inside Dockerfiles while creating derivatives. This ideally can take optional arguments as packages, but should provide a out of the box working experience covering minimal needs

Cloud-init, user-features:
- [x] #942
- [x] #987
- [ ] `elemental features {enable,disable,list} $feature`: port current `cos-features`

Core features:
- [x] #997
- [x] #905
- [x] #941
- [x] #1049

Plugins:
- [ ] `elemental-plugin-cosign`: reuse/port cosign plugin as library
- [ ] `elemental-plugin-mtree`: reuse/port mtree plugin as library

Nice to have:
- [ ] `elemental new`: Create skeleton Dockerfile for a derivative (with customizable arch, flavor, etc)
- [x] #1305

#### dependent issues

- #155 (yq)
- #157 (yq)
- #174 (cloud images)
- #182 (image verification plugin)
- https://github.com/rancher-sandbox/cOS-toolkit/pull/312
- #449

**Comment by Itxaka** [comment]
@davidcassany @kkaempf I think we should close this. Do we expect to implement the elemental build and install-packages command into elemental any time?

I mean, we dont seem to use them or need them anywhere really as to make them a needed feature, cosign is already in IIRC, mtree is kind of not used for now anywhere, and the new command was already implemented.

**Comment by kkaempf** [comment]
Agreed.
