### ISSUE TITLE
Sync elemental-cli and elemental-installer

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-toolkit#1347]
Currently elemental-cli and elemental-installer are out of sync, specially regarding the environmental variables usage. So far I noted ros-installer aims to make use of:

form `pkg/config/read.go`
* `ELEMENTAL_CLOUD_INIT`: to define an extra cloud-init config to include within the installation
* `ELEMENTAL_ISO`: to define the URI of an ISO to use as a source for the installation
* `ELEMENTAL_POWEROFF`: set poweroff after install operation
* `ELEMENTAL_TARGET`: to set the target device for the installation
* `ELEMENTAL_DOCKER_IMAGE`: to set a docker source as the OS image for the installation
* `ELEMENTAL_FORCE_EFI`: to set EFI firmware during install
* `ELEMENTAL_NO_FORMAT:` to prevent formatting during installation
* `ELEMENTAL_DEBUG`: to set debug flag in elemental
* `ELEMENTAL_TTY`: to set an extra console in kernel parameters
* `ELEMENTAL_REGISTRATION_URL`: I don't think this relates to elemental in any way.

As a result of rancher-sandbox/elemental#189 these environment variables are not valid anymore. Assuming we need to keep all the variables from the above list they could easily be mapped to:

* `ELEMENTAL_CLOUD_IINIT` -> `ELEMENTAL_INSTALL_CLOUD_INIT`
* `ELEMENTAL_TARGET` -> `ELEMENTAL_INSTALL_TARGET`
* `ELEMENTAL_POWEROFF` -> keep it as is
* `ELEMENTAL_ISO` ->  `ELEMENTAL_INSTALL_ISO`
* `ELEMENTAL_DOCKER_IMAGE` -> `ELEMENTAL_INSTALL_SYSTEM` (and the value expects a `docker:<image-ref>`)
* `ELEMENTAL_FORCE_EFI` -> `ELEMENTAL_INSTALL_FIRMWARE` (and the value expects `efi|bios`)
* `ELEMENTAL_NO_FORMAT` -> `ELEMENTAL_INSTALL_NO_FORMAT`
* `ELEMENTAL_DEBUG` -> keep it as is
* `ELEMENTAL_TTY` -> `ELEMENTAL_INSTALL_TTY`
* `ELEMENTAL_REGISTRATION_URL` -> drop it, I don think it relates to elemental in any way

Note that installation specific data has a the `ELEMENTAL_INSTALL_` prefix, I did it this way to prevent clashing variables across commands, but probably this is not a problem.

Just provide and example `elemental install` supports `ELEMENTAL_INSALL_SYSTEM` variable and `elemental upgrade` supports `ELEMENTAL_UPGRADE_SYSTEM` variable, this way we can define the installation and upgrade system independently.

From an environment variables perspective is is probably reasonable to accept that `ELEMENTAL_SYSTEM` could be applied for `elemental upgrade` and `elemental install` as it is unlikely that both commands are executed in a row within the same environment. If this is acceptable the above list of conversions is really simplified. I vote for this option, but realize this is going to be hard to change afterwards if we experience undesired variables collisions across commands (I don't think this is going to happen though).

Another option could be being slightly inconsistent and use `ELEMENTAL_SYSTEM` for the installation and `ELEMENTAL_UPGRADE_SYSTEM` for the upgrade.

Regarding the image reference syntax change we can try to be backward compatible in elemental (like assuming docker type if undefined or some similar criteria) or simply modify ros-installer to prepend the `docker:` scheme to the image reference uri.

### Tasks:

- [x] agree on the supported variables set
- [x] add those variables into elemental maps `pkg/constants/constants.go`
- [x] code tests for all of them (in `cmd/config/config_test.go`)
- [ ] adapt ros-installer (if needed)
- [ ] backport PRs from ros-installer to the new repository
- [ ] tag new elemental-cli version
- [ ] bump OBS testing packages

**Comment by davidcassany** [comment]
Implementation wise this is a chore, probably testing requires some time, but coding it is should be really straight forward, specially if we agree to minimize the impact on ros-installer.

**Comment by mudler** [comment]
Blocked until `ros-installer` finds a final location

**Comment by mudler** [comment]
the `ros-installer` final location will be inside the ros-operator repository. Although, we are in the middle of migrating and the ros-installer code isn't there (yet)

**Comment by mudler** [comment]
We might have also to backport:

- https://github.com/rancher-sandbox/ros-installer/pull/1  (already merged)
- https://github.com/rancher-sandbox/ros-installer/pull/2 (to merge)

**Comment by mudler** [comment]
Blocked by https://github.com/rancher/elemental/issues/136

**Comment by davidcassany** [comment]
Since ros-installer is not yet merged to elementa-operator and the repository is in archived mode I created a fork with the expectations of the change set required for this card in here https://github.com/davidcassany/ros-installer/pull/1. Note this has not been validated yet.

Note in former ros-installer the `config.Install.ContainerImage` field expects an image reference, so it can't be mapped directly to `ELEMENTAL_INSTALL_SYSTEM` which expects a URI (e.g. `docker:<imageref>`).

@mudler correct me if I am wrong, but I assume the filed `config.Install.ContainerImage` should remaing being a simple container reference, I don't expect to use `channel` or `dir` source types within the context of the elemental-operator, so adding a `docker` scheme is just cumbersome. If this is the case then the syntax of `config.Install.ContainerImage` should remaing untouched meaning we need a way to convert the given image reference into something understandable to `elemental-cli`. I foresee a couple of options:

1. Turn image registry references into the default source type in `elemental-cli`, that is, from an `elemental-cli` PoV the following two configs mean the same:

```yaml
install:
  system:
    uri: docker:registry.org/my/image:tag
```

```yaml
install:
  system:
    uri: registry.org/my/image:tag
```

I think this is a reasonable option for `elemental-cli`, this is already the case for the `build-iso` command. We can extend it to all commands.

2. Make the unmarshall process of the installer here to prepend a `docker:` prefix in any value given for `config.Install.ContainerImage`. So assume there is a conversion to elemental-cli syntax somewhere in the code. I don't like the idea, I find it too obscure.

**Comment by davidcassany** [comment]
Now elemental when unmarshaling sources fallsback to treat it as a docker registry image reference if the given value does not match not match any of the known schemes (`docker`, `file`, `channel` or `dir`) or it fails to parse it as a URI. In addition it also defaults to `latest` tag if no tag is given.

**Comment by mudler** [comment]
> Since ros-installer is not yet merged to elementa-operator and the repository is in archived mode I created a fork with the expectations of the change set required for this card in here [davidcassany/ros-installer#1](https://github.com/davidcassany/ros-installer/pull/1). Note this has not been validated yet.
> 
> Note in former ros-installer the `config.Install.ContainerImage` field expects an image reference, so it can't be mapped directly to `ELEMENTAL_INSTALL_SYSTEM` which expects a URI (e.g. `docker:<imageref>`).
> 
> @mudler correct me if I am wrong, but I assume the field `config.Install.ContainerImage` should remain being a simple container reference, I don't expect to use `channel` or `dir` source types within the context of the elemental-operator, so adding a `docker` scheme is just cumbersome. If this is the case then the syntax of `config.Install.ContainerImage` should remain untouched meaning we need a way to convert the given image reference into something understandable to `elemental-cli`. I foresee a couple of options:
> 
>     1. Turn image registry references into the default source type in `elemental-cli`, that is, from an `elemental-cli` PoV the following two configs mean the same:
> 
> 
> ```yaml
> install:
>   system:
>     uri: docker:registry.org/my/image:tag
> ```
> 
> ```yaml
> install:
>   system:
>     uri: registry.org/my/image:tag
> ```
> 
> I think this is a reasonable option for `elemental-cli`, this is already the case for the `build-iso` command. We can extend it to all commands. Did a PR for that here [rancher/elemental-cli#264](https://github.com/rancher/elemental-cli/pull/264)
> 
>     2. Make the unmarshall process of the installer here to prepend a `docker:` prefix in any value given for `config.Install.ContainerImage`. So assume there is a conversion to elemental-cli syntax somewhere in the code. I don't like the idea, I find it too obscure.

It is totally safe to assume `config.Install.ContainerImage` has only container images as input. Alternatively we can also think about extending the install with another field to provide a source field which is mapped 1:1 with elemental, but the usage here is limited to containers, the boot live medium itself, and an ISO file as a source of installation, so it sounds ok to keep it as is too.

**Comment by davidcassany** [comment]
The code from https://github.com/davidcassany/ros-installer/pull/1 is already part of `elemental-operator` and a successful communication between the elemental-cli wrapper and elemental-cli is already functional (despite not all flags and variables have been completely validated, there could be some small mismatch on variables names).

Note is has been managed in the scope of rancher/elemental-operator#7. Closing since all the essential logic related to this specific task is already in place.
