### ISSUE TITLE
[epic] Drive elemental-toolkit to v1.x

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-toolkit#1738]
/This is an epic to mostly track actionable items towards https://github.com/rancher/elemental-toolkit/discussions/1716

The work done here can be based on top of this [PoC](https://github.com/davidcassany/elemental-toolkit/pull/3) started in Hackweek.

Actionable prior merge items:
- [x] Set a working branch with new _package_ names if suitable
- Expand the PR test matrix to cover (keep all of them easily executable on a local env)
  - [x] rancher/elemental-toolkit#1756
- [x] Adapt OBS builds of the elemental-toolkit package

- [x] Set a nightly build workflow on main (same test matrix as in PRs) x86_64 and aarch64
- [x] Drop `luet`

After merging:
- [x] #1762
- [x] rancher/elemental-toolkit#1766
- [x] rancher/elemental-toolkit#1754
- [x] rancher/elemental-toolkit#1755
- [x] #1792
- [x] #1793
- [x] https://github.com/rancher/elemental-toolkit/issues/1805 (move green example to 15.5 and add TW)

**Comment by mbologna** [comment]
- [ ] Do the actual release
