### ISSUE TITLE
[epic] Elemental-toolkit next generation

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-toolkit#1863]
This is a collection of all the tasks required in elemental-toolkit to better align it with upcoming SUSE distributions and other still pending improvements.

- [x] #1781 (arranged with #1844)
- [x] #1848
- [x] #1928
- [x] #1874
- [x] #1923
- [x] #1921
- [x] #1922
- [x] #1865
- [x] #1925
- [x] #1927
- [x] #1895

A nice to have:

- [ ] #1930
- [ ] Refactor cloud-init-paths flag to some hooks specific concept
- [x] Move elemental-setup-* service files to /etc (#1896)
- [ ] Get rid of all COS references in the code (default labels, paths, etc.)
- [ ] #1864
- [ ] Make use of fixed UUIDs for partitions based on [Discoverable Partitions Spec](https://www.freedesktop.org/wiki/Specifications/DiscoverablePartitionsSpec)
- [ ] Support systemd-boot
- [ ] scheduled CI for arm64

**Comment by bk201** [comment]
> Get rid of all COS references in the code (default labels, paths, etc.)

Hi David, will this break the current running clusters or there will be an upgrade solution? Harvester nodes are all running with `COS_` labels and we still need to support existing customers.

**Comment by davidcassany** [comment]
@bk201 we are in the process of aligning with the upcoming SUSE distributions, hence it will include relevant refactors of the code and likely to lead us to a v2 version of the toolkit. There are some challenging changes ahead. These are not immediate changes and we already added in high prio setting a proper upgrade test in our CI, so we can detect breaking changes and define proper backward compatibility considerations and constraints. 

Regarding the `COS_` labels they are configurable and tracked within the `state.yaml` file. So elemental client reads and applies the labels from there on installed systems. This was already put in place at a time to allow changing default labels without breaking backward compatibility.

**Comment by bk201** [comment]
@davidcassany Thanks for the explanation.

**Comment by kkaempf** [comment]
Closing this issue as we've reached ['v2' for toolkit](https://github.com/rancher/elemental-toolkit/issues/1927)

**Comment by bk201** [comment]
@davidcassany From https://github.com/rancher/elemental-toolkit/issues/1927, there seem to be some breaking changes. Does this mean we can't upgrade from v1 to v2? And is v1 going to be maintained in the future? Thanks!

**Comment by kkaempf** [comment]
@bk201 there shouldn't be breaking changes and you should be able to upgrade from v1 to v2.
We might do bug fixes in v1 (none are planned at this time) but actually want everyone to move to v2 in the future.

**Comment by bk201** [comment]
Thank you for the explanation!
