### ISSUE TITLE
Enhance debugging experience

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-toolkit#7]
Debugging experience is a large topic, it goes from the building process to cOS usage, and derivative debugging too. This epic is a ticket trying to collect all the Sub/issues and enhancement around enhancing the debugging experience in the project areas:

Building:
- [x] https://github.com/mudler/luet/issues/162
- [x] Print informative message on build failure in https://github.com/mudler/luet to give directions on how to debug with the above extension
- [x] https://github.com/mudler/luet/issues/164

Usage:
- [x] #388 
- [ ] #389

**Comment by kkaempf** [comment]
closing since only #389 is still open
